server:
  port:   9000
  servlet:
    context-path: /phonebook
spring:
  messages:
    basename: validations
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
